spring:
  application:
    name: SpringAi-chat-DeepSeek
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:7b
logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    com.wart.ai: debug